// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH8aPJ6MOss8QstVZ_U838Q7VTnuLUQ5o',
    appId: '1:4427713198:web:6f458a6fe5a76bdfc47b3f',
    messagingSenderId: '4427713198',
    projectId: 'kkdkparcel',
    authDomain: 'kkdkparcel.firebaseapp.com',
    storageBucket: 'kkdkparcel.firebasestorage.app',
    measurementId: 'G-JH0EQK94W9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvC62GmBbxo1A5rCplAYW_izaPxCyKkGk',
    appId: '1:4427713198:android:d8390271a96d0cebc47b3f',
    messagingSenderId: '4427713198',
    projectId: 'kkdkparcel',
    storageBucket: 'kkdkparcel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM4OdUAqGTYmceVMj3L7S35R0g5Sm2G1Q',
    appId: '1:4427713198:ios:214888aec357a75dc47b3f',
    messagingSenderId: '4427713198',
    projectId: 'kkdkparcel',
    storageBucket: 'kkdkparcel.firebasestorage.app',
    iosBundleId: 'com.example.kkdk.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM4OdUAqGTYmceVMj3L7S35R0g5Sm2G1Q',
    appId: '1:4427713198:ios:214888aec357a75dc47b3f',
    messagingSenderId: '4427713198',
    projectId: 'kkdkparcel',
    storageBucket: 'kkdkparcel.firebasestorage.app',
    iosBundleId: 'com.example.kkdk.flutterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH8aPJ6MOss8QstVZ_U838Q7VTnuLUQ5o',
    appId: '1:4427713198:web:77914ee03a5c1233c47b3f',
    messagingSenderId: '4427713198',
    projectId: 'kkdkparcel',
    authDomain: 'kkdkparcel.firebaseapp.com',
    storageBucket: 'kkdkparcel.firebasestorage.app',
    measurementId: 'G-35M1ZTXWG0',
  );


}
